### ISSUE TITLE
Unexpected exception importing component custom_components.anycubic_wifi

### ISSUE THREAD

**Issue by WegnerDan** [adamoutler/anycubic-homeassistant#1]
Got this error after the last update:

![image](https://user-images.githubusercontent.com/6908247/174303311-1e807cf2-7013-4136-a7d4-cfc197219dbe.png)
```
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/anycubic_wifi/api.py:10
Integration: Anycubic 3D Printer
First occurred: 13:32:57 (1 occurrences)
Last logged: 13:32:57

Unexpected exception importing component custom_components.anycubic_wifi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/anycubic_wifi/__init__.py", line 13, in <module>
    from .device import AnycubicUartWifiDevice
  File "/config/custom_components/anycubic_wifi/device.py", line 8, in <module>
    from .api import MonoXAPI
  File "/config/custom_components/anycubic_wifi/api.py", line 10, in <module>
    _LOGGER = logging.getLogger(__name__)
NameError: name 'logging' is not defined
```

**Comment by adamoutler** [comment]
Sorry. That wasn't supposed to be pushed out.

**Comment by WegnerDan** [comment]
Last commit fixed it, thanks!

I'm just happy you made this integration.

**Comment by adamoutler** [comment]
Check out my addon as well.  It does the same things and let's you start and monitor prints.
