### ISSUE TITLE
integration does not work with firmware 3.5.4

### ISSUE THREAD

**Issue by wildblue** [adamoutler/anycubic-homeassistant#3]
Got printer, installed integration.
it displayed FW v3.4.8.
Then updated FW of Mono X.
checked integration, but it still displayed v3.4.8.
restarted integration.
restarted HA.
still 3.4.8 displayed.
removed integration.
restarted HA.
tried to install integration:
entered ip
Unknown error occurred

log entry:
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: aiohttp.server
Source: custom_components/anycubic_wifi/config_flow.py:116
Integration: Anycubic 3D Printer
First occurred: 16:44:40 (4 occurrences)
Last logged: 16:58:18

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/anycubic_wifi/config_flow.py", line 91, in async_step_user
    configured: bool = await self.async_step_duplicates(user_input)
  File "/config/custom_components/anycubic_wifi/config_flow.py", line 116, in async_step_duplicates
    await self.async_set_unique_id(device[CONF_SERIAL])
KeyError: 'serial_number'

**Comment by adamoutler** [comment]
From SSH and Web Terminal, try typing `nc IP.ADD.RE.SS 6000` (where IP.ADD.RE.SS is your printer's IP), followed by `sysinfo` and then enter.    What does it say?  Eg. 
![image](https://user-images.githubusercontent.com/527919/188322636-1f0fe2fe-e58d-425a-b70e-93713d776b8f.png)

You can also try `getstatus`, and `getfiles` as well.

**Comment by WegnerDan** [comment]
I have a Photon Mono X on Firmware 3.5.4 and this integration works with it.
