### ISSUE TITLE
Unknown error with Anycubic Photon Mono M5s

### ISSUE THREAD

**Issue by msavazzi** [adamoutler/anycubic-homeassistant#6]
When I try to add the Anycubic Photon Mono M5s I get an "unknown error".
https://www.anycubic.com/products/photon-mono-m5s

even is if a Mono.

Can you help?
M

**Comment by msavazzi** [comment]
I got this in the log
```
2023-12-16 16:25:52.561 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/uart_wifi/communication.py", line 124, in _do_request
sock = _setup_socket(socket_address)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/uart_wifi/communication.py", line 191, in _setup_socket
sock.connect(socket_address)
TimeoutError: timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 389, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/anycubic_wifi/config_flow.py", line 91, in async_step_user
configured: bool = await self.async_step_duplicates(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/anycubic_wifi/config_flow.py", line 113, in async_step_duplicates
self._add_device_info_to_device(device)
File "/config/custom_components/anycubic_wifi/config_flow.py", line 138, in _add_device_info_to_device
system_information: MonoXSysInfo() = adapter.sysinfo()
^^^^^^^^^^^^^^^^^
File "/config/custom_components/anycubic_wifi/adapter_fascade.py", line 90, in sysinfo
response = self.send_request("sysinfo,\r\n")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/uart_wifi/communication.py", line 78, in send_request
return_value = self._send_request(message_to_be_sent)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/uart_wifi/communication.py", line 87, in _send_request
return_value = self._async_send_request(message)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/uart_wifi/communication.py", line 99, in _async_send_request
received: str = _do_request(
^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/uart_wifi/communication.py", line 157, in _do_request
raise ConnectionException(
uart_wifi.errors.ConnectionException: Could not connect to AnyCubic printer at 192.168.2.173
```

**Comment by andyearnshaw** [comment]
Same here. I think the addon is designed to work with Mono X printers only at the moment. @adamoutler, please let me know how I might go about adding support for the M5s.

**Comment by adamoutler** [comment]
The Mono X uses Uart-WiFi, a telnet-like local control mechanism. It works like a serial port and requires constant polling to get status. 

The M5s uses MQTT in the cloud. It uses an event based system to push updates.  


They're not compatible.  Not even slightly.  

The things you'd want to do with one printer are completely different than the other due to design decisions.  This project will only work for Uart-WiFi devices and would be redesigned to work with cloud-based devices.

**Comment by andyearnshaw** [comment]
@adamoutler thanks for the quick response. Did you make any further progress with the M5s than outlined in [this reddit comment](https://www.reddit.com/r/AnycubicPhotonMono/comments/165uw3c/comment/jzdfzbl/?utm_source=reddit&utm_medium=web2x&context=3)?

> Something else that comes to mind is use the hosts file to convince the device that anycubic cloud exists on localhost, place a new MQTT server on the device via telnet and then just use MQTT to communicate. This would be more intrusive.  

If it were as simple as that, we could go a less intrusive route with a local DNS server, right?

> However, I'm certain that, time permitting, this device will have local support without cloud

Here's hoping!

**Comment by adamoutler** [comment]
It would be possible to redirect to a local server.  The DNS is right on the printer because it runs OpenWRT.  The thing is, I don't know how to access the raw printer variables. If I did, we could make it work very easily with some sort of adapter.  It would work way better than MonoX ever did. But within the shell, I'm not able to find what I want.

**Comment by andyearnshaw** [comment]
DNS on the printer just forwards to the router. I can get the printer to try to connect to my local mosquitto instance just by listening on port 8883 and then mapping the hostname `mqtt-universe.anycubic.com` to the IP address of the machine mosquitto is running on.

```
1704021811: New connection from 192.168.1.238:45415 on port 8883.
1704021811: Client <unknown> disconnected due to protocol error.
```

I suspect this is because I haven't set up SSL, which I will attempt to do if I have time today. Even then, if the printer is set up to validate the cert against the hostname then it probably still won't connect and would require messing with the certs on the printer.

If you can't set up hostname mapping on your router (my router is also running OpenWrt), you could try running dnsmasq somewhere and pointing your router's DNS server configuration to that.

> But within the shell, I'm not able to find what I want.

Did you try finding the process that's connecting to the anycubic mqtt server? I wonder if it's got any open device/file handles that you could see using `lsof -P -n -p <PID>`, then try to access them yourself.

**Comment by andyearnshaw** [comment]
DNS overriding is almost definitely a dead end without modifying the printer. It looks like Anycubic is using a custom CA with generated certs embedded in the firmware.

**Comment by msavazzi** [comment]
Thank you! 
I'm sorry it uses MQTT
Were you able to do anything ?

**Comment by adamoutler** [comment]
Well, here's a thing!  This shows progress percent, remaining time, and many other stats which would be useful.

![image](https://github.com/adamoutler/anycubic-homeassistant/assets/527919/eb978e2e-d97f-466c-b557-ea5a517ffc80)

It would not be proper for me to disclose the password right now. I have disclosed the weak password to Anycubic and they have not released an update since.  It is a security vulnerability as it potentially allows a hacker to perform denial of service and possibly more control over your device than you have. 

I used the ssh password to poke around at the various processes on the device. Within the `comm` process I looked at open files.  I found it had a file within `/usr/sbin/LOG` opened.  I checked the log and found some JSON within the log.  This is what we're after for local monitoring. 

Here's the command above.
`ssh root@192.168.1.137 -oKexAlgorithms=+diffie-hellman-group14-sha1 'cat /usr/sbin/LOG/"$(ls -1t /usr/sbin/LOG/|head -n1)"| grep "playlad"|tail -n1|sed -e "s/.*playlad: //"'|jq`

Here's a command to turn your terminal into a JSON api
`ssh root@192.168.1.137 -oKexAlgorithms=+diffie-hellman-group14-sha1 'tail -f /usr/sbin/LOG/"$(ls -1t /usr/sbin/LOG/|head -n1)"'|grep playlad|sed 's/.*playlad: //g'`
![image](https://github.com/adamoutler/anycubic-homeassistant/assets/527919/f1b5bc5e-758c-4f31-ba13-eff5f81a1180)


If you'd like to see this made into something useful, Ask anycubic to make this available as a user.  there's no reason we shouldn't be able to use telnet to view/tail the logs within the /usr/sbin/LOG. I honestly don't have time, so I need you to help.  We should be able to log in to telnet `logs@ip.add.res.ss` and read the current logs and that's really easy to do with the existing setup.

Let me repeat.  If you want to see a home assistant addon, or any sort of tool, send a message to Anycubic Support. Ask them for local telnet/http access to the /usr/bin/LOG logs so that you can monitor your printer with your home automation system.  

https://www.anycubic.com/pages/contact-us

**Comment by KairuByte** [comment]
@adamoutler it's been a year, have they bothered to patch the entry point yet? I've not checked myself, but I'm willing to bet getting that password wasn't that difficult in the first place, and anyone running these devices are running them walled off from the open internet. I'd say the point of responsible disclosure is long since past if they've still not handled the issue.

**Comment by adamoutler** [comment]
Sure.  It was easy.  I asked for a copy of the firmware to upgrade.  I took it apart and gained access to the filesystem.  I pulled the /etc/passwd file and put it into jack the ripper. I added mission-specific phrases to it such as anycubic, 3D, 3dprinter and a few more.  Within 2 minutes the password was broken.  I'm not going to directly write it, but it's "anycubic"  followed by the year the software was originally written.
