### ISSUE TITLE
Integration won't load after HA upgrade to 2024.1.3

### ISSUE THREAD

**Issue by collinstork** [adamoutler/anycubic-homeassistant#7]
After updating to HA 2024.1.3, I am getting the following error:

Unexpected exception importing platform custom_components.anycubic_wifi.sensor
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/anycubic_wifi/sensor.py", line 17, in <module>
    from .base_entry_decorator import AnycubicEntityBaseDecorator
  File "/config/custom_components/anycubic_wifi/base_entry_decorator.py", line 20, in <module>
    class AnycubicEntityBaseDecorator(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in __init__
    wrap_attr(cls, property_name)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in wrap_attr
    raise TypeError(f"Can't override {attr_name} in subclass")
TypeError: Can't override _attr_entity_picture in subclass
```

**Comment by adamoutler** [comment]
Can confirm. However, I do not use this addon anymore. I switched to the MonoX M5s.  I'm examining ways to make the new one work, but not yet having luck.   

I'm sorry but I can't make changes that I can be sure will work.
